# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kaushik/Repositories/decagt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kaushik/Repositories/decagt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"python3\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kaushik/Repositories/decagt/CMakeFiles /Users/kaushik/Repositories/decagt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kaushik/Repositories/decagt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named decagt

# Build rule for target.
decagt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 decagt
.PHONY : decagt

# fast build rule for target.
decagt/fast:
	$(MAKE) -f CMakeFiles/decagt.dir/build.make CMakeFiles/decagt.dir/build
.PHONY : decagt/fast

src/core/bindings.o: src/core/bindings.cc.o

.PHONY : src/core/bindings.o

# target to build an object file
src/core/bindings.cc.o:
	$(MAKE) -f CMakeFiles/decagt.dir/build.make CMakeFiles/decagt.dir/src/core/bindings.cc.o
.PHONY : src/core/bindings.cc.o

src/core/bindings.i: src/core/bindings.cc.i

.PHONY : src/core/bindings.i

# target to preprocess a source file
src/core/bindings.cc.i:
	$(MAKE) -f CMakeFiles/decagt.dir/build.make CMakeFiles/decagt.dir/src/core/bindings.cc.i
.PHONY : src/core/bindings.cc.i

src/core/bindings.s: src/core/bindings.cc.s

.PHONY : src/core/bindings.s

# target to generate assembly for a file
src/core/bindings.cc.s:
	$(MAKE) -f CMakeFiles/decagt.dir/build.make CMakeFiles/decagt.dir/src/core/bindings.cc.s
.PHONY : src/core/bindings.cc.s

src/core/core_utils.o: src/core/core_utils.cc.o

.PHONY : src/core/core_utils.o

# target to build an object file
src/core/core_utils.cc.o:
	$(MAKE) -f CMakeFiles/decagt.dir/build.make CMakeFiles/decagt.dir/src/core/core_utils.cc.o
.PHONY : src/core/core_utils.cc.o

src/core/core_utils.i: src/core/core_utils.cc.i

.PHONY : src/core/core_utils.i

# target to preprocess a source file
src/core/core_utils.cc.i:
	$(MAKE) -f CMakeFiles/decagt.dir/build.make CMakeFiles/decagt.dir/src/core/core_utils.cc.i
.PHONY : src/core/core_utils.cc.i

src/core/core_utils.s: src/core/core_utils.cc.s

.PHONY : src/core/core_utils.s

# target to generate assembly for a file
src/core/core_utils.cc.s:
	$(MAKE) -f CMakeFiles/decagt.dir/build.make CMakeFiles/decagt.dir/src/core/core_utils.cc.s
.PHONY : src/core/core_utils.cc.s

src/core/discrete_exterior_calculus.o: src/core/discrete_exterior_calculus.cc.o

.PHONY : src/core/discrete_exterior_calculus.o

# target to build an object file
src/core/discrete_exterior_calculus.cc.o:
	$(MAKE) -f CMakeFiles/decagt.dir/build.make CMakeFiles/decagt.dir/src/core/discrete_exterior_calculus.cc.o
.PHONY : src/core/discrete_exterior_calculus.cc.o

src/core/discrete_exterior_calculus.i: src/core/discrete_exterior_calculus.cc.i

.PHONY : src/core/discrete_exterior_calculus.i

# target to preprocess a source file
src/core/discrete_exterior_calculus.cc.i:
	$(MAKE) -f CMakeFiles/decagt.dir/build.make CMakeFiles/decagt.dir/src/core/discrete_exterior_calculus.cc.i
.PHONY : src/core/discrete_exterior_calculus.cc.i

src/core/discrete_exterior_calculus.s: src/core/discrete_exterior_calculus.cc.s

.PHONY : src/core/discrete_exterior_calculus.s

# target to generate assembly for a file
src/core/discrete_exterior_calculus.cc.s:
	$(MAKE) -f CMakeFiles/decagt.dir/build.make CMakeFiles/decagt.dir/src/core/discrete_exterior_calculus.cc.s
.PHONY : src/core/discrete_exterior_calculus.cc.s

src/core/finite_element_exterior_calculus.o: src/core/finite_element_exterior_calculus.cc.o

.PHONY : src/core/finite_element_exterior_calculus.o

# target to build an object file
src/core/finite_element_exterior_calculus.cc.o:
	$(MAKE) -f CMakeFiles/decagt.dir/build.make CMakeFiles/decagt.dir/src/core/finite_element_exterior_calculus.cc.o
.PHONY : src/core/finite_element_exterior_calculus.cc.o

src/core/finite_element_exterior_calculus.i: src/core/finite_element_exterior_calculus.cc.i

.PHONY : src/core/finite_element_exterior_calculus.i

# target to preprocess a source file
src/core/finite_element_exterior_calculus.cc.i:
	$(MAKE) -f CMakeFiles/decagt.dir/build.make CMakeFiles/decagt.dir/src/core/finite_element_exterior_calculus.cc.i
.PHONY : src/core/finite_element_exterior_calculus.cc.i

src/core/finite_element_exterior_calculus.s: src/core/finite_element_exterior_calculus.cc.s

.PHONY : src/core/finite_element_exterior_calculus.s

# target to generate assembly for a file
src/core/finite_element_exterior_calculus.cc.s:
	$(MAKE) -f CMakeFiles/decagt.dir/build.make CMakeFiles/decagt.dir/src/core/finite_element_exterior_calculus.cc.s
.PHONY : src/core/finite_element_exterior_calculus.cc.s

src/core/geometry.o: src/core/geometry.cc.o

.PHONY : src/core/geometry.o

# target to build an object file
src/core/geometry.cc.o:
	$(MAKE) -f CMakeFiles/decagt.dir/build.make CMakeFiles/decagt.dir/src/core/geometry.cc.o
.PHONY : src/core/geometry.cc.o

src/core/geometry.i: src/core/geometry.cc.i

.PHONY : src/core/geometry.i

# target to preprocess a source file
src/core/geometry.cc.i:
	$(MAKE) -f CMakeFiles/decagt.dir/build.make CMakeFiles/decagt.dir/src/core/geometry.cc.i
.PHONY : src/core/geometry.cc.i

src/core/geometry.s: src/core/geometry.cc.s

.PHONY : src/core/geometry.s

# target to generate assembly for a file
src/core/geometry.cc.s:
	$(MAKE) -f CMakeFiles/decagt.dir/build.make CMakeFiles/decagt.dir/src/core/geometry.cc.s
.PHONY : src/core/geometry.cc.s

src/core/simplicial_complex.o: src/core/simplicial_complex.cc.o

.PHONY : src/core/simplicial_complex.o

# target to build an object file
src/core/simplicial_complex.cc.o:
	$(MAKE) -f CMakeFiles/decagt.dir/build.make CMakeFiles/decagt.dir/src/core/simplicial_complex.cc.o
.PHONY : src/core/simplicial_complex.cc.o

src/core/simplicial_complex.i: src/core/simplicial_complex.cc.i

.PHONY : src/core/simplicial_complex.i

# target to preprocess a source file
src/core/simplicial_complex.cc.i:
	$(MAKE) -f CMakeFiles/decagt.dir/build.make CMakeFiles/decagt.dir/src/core/simplicial_complex.cc.i
.PHONY : src/core/simplicial_complex.cc.i

src/core/simplicial_complex.s: src/core/simplicial_complex.cc.s

.PHONY : src/core/simplicial_complex.s

# target to generate assembly for a file
src/core/simplicial_complex.cc.s:
	$(MAKE) -f CMakeFiles/decagt.dir/build.make CMakeFiles/decagt.dir/src/core/simplicial_complex.cc.s
.PHONY : src/core/simplicial_complex.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... decagt"
	@echo "... src/core/bindings.o"
	@echo "... src/core/bindings.i"
	@echo "... src/core/bindings.s"
	@echo "... src/core/core_utils.o"
	@echo "... src/core/core_utils.i"
	@echo "... src/core/core_utils.s"
	@echo "... src/core/discrete_exterior_calculus.o"
	@echo "... src/core/discrete_exterior_calculus.i"
	@echo "... src/core/discrete_exterior_calculus.s"
	@echo "... src/core/finite_element_exterior_calculus.o"
	@echo "... src/core/finite_element_exterior_calculus.i"
	@echo "... src/core/finite_element_exterior_calculus.s"
	@echo "... src/core/geometry.o"
	@echo "... src/core/geometry.i"
	@echo "... src/core/geometry.s"
	@echo "... src/core/simplicial_complex.o"
	@echo "... src/core/simplicial_complex.i"
	@echo "... src/core/simplicial_complex.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

